project:
  type: book
  output-dir: docs

book:
  title: "Workshop de Graficas Interactivas y articulos"
  author: "Evelia Coss"
  date: "6/7/2025"
  page-navigation: true
  chapters:
    - index.qmd
    - salvavidas.qmd
    - tema1.qmd
    - part: "Gráficas interactivas"
      chapters:
      - Cap1_plotly.qmd
      - Cap2_ggiraph_p1.qmd
      - Cap3_ggiraph_p2.qmd
      - Cap4_ggiraph_examples.qmd
    - part: "Ejemplos de articulos"
      chapters:
      - tema2.qmd
      - Cap5_QuartoJournals.qmd
      - Cap6_Completefigure.qmd
  # Information
  repo-url: https://github.com/EveliaCoss/Workshop_GraficasInteractivas_papers # link de Github
  sharing: [twitter, facebook, linkedin]
  favicon: "figures/LIIGHUNAM_logo.png" # icono de la pagina en pestana

format:
  html:
    logo: "figures/LIIGHUNAM_logo.png"
    toc-depth: 4
    number-depth: 3
  # Boton para cambiar tema de oscuro a claro
    theme:
      light: cosmo
      dark: darkly
    code-fold: show # Ocultar codigo
    code-copy: true # Copy button
    freeze: false  # Desactivar congelamiento

editor: visual

